name=SpanCast
version=1.0.0
author=Gregg <homespan@icloud.com>
maintainer=Gregg <homespan@icloud.com>
sentence=An extremely easy-to-use peer-to-peer messaging protocol for the ESP32 and ESP8266 running under the Arduino IDE.
paragraph=This library provides a full-function peer-to-peer messaging protocol based on Espressif's ESP-NOW framework.  Key benefits of SpanCast include automated WiFi channel selection, message verification, and the use of user-defined device IDs instead of having chip-based MAC addresses hardcoded into each sketch.  SpanCast can operate on a standalone basis though works especially well with HomeSpan allowing you to connect custom, remote (battery-operated) sensors directly to Apple HomeKit. SpanCast runs under the Arduino IDE and supports the ESP8266, the original ESP32, and the following ESP32 variants: S2, S3, C3, C5 and C6.
url=https://github.com/HomeSpan/SpanCast
architectures=esp32,esp8266
includes=SpanCast.h
